#!/bin/sh
#
# This file will create the $OUTPUT_FILENAME_* with some runtime variables

OUTPUT_FILENAME_HEADER="Inc/versioncc.h"
OUTPUT_FILENAME_SOURCE="versioncc.c"
PATH_OUTPUT_FILENAME_SOURCE="Src/$OUTPUT_FILENAME_SOURCE"

cd ..
PWD=$(pwd)

#export GITHASH="$(git rev-parse --verify HEAD)"
#echo "HASH: $GITHASH"

TIMESTAMP_ISO=$(date -Iseconds)
DATE=$(date +"%Y-%m-%d")
DATE_YEAR=$(date +"%Y")
DATE_MONTH=$(date +"%m")
DATE_DAY=$(date +"%d")



if [ ! -f $PWD/.buildnum ]; then
    touch .buildnum
    echo 1 > .buildnum
fi
BUILDNUMBER=$(cat .buildnum)
BUILDNUMBER=$((BUILDNUMBER+1)) > $PWD/.buildnum
#echo "const uint16_t __BUILD_NUMBER__ APPINFO_BUILDID_ATTR = $BUILDNUMBER;" >> $PATH_OUTPUT_FILENAME_SOURCE
echo $BUILDNUMBER > $PWD/.buildnum

echo "/**" > $OUTPUT_FILENAME_HEADER
echo " * @file versioncc.h" >> $OUTPUT_FILENAME_HEADER
echo " * @author fl0mll" >> $OUTPUT_FILENAME_HEADER
echo " * @date $DATE" >> $OUTPUT_FILENAME_HEADER
echo " * @copyright" >> $OUTPUT_FILENAME_HEADER
echo " *" >> $OUTPUT_FILENAME_HEADER
echo " * @brief Compiler Definitions generated by (pre) build script" >> $OUTPUT_FILENAME_HEADER
echo " */" >> $OUTPUT_FILENAME_HEADER
echo "#ifndef __VERSIONCC__" >> $OUTPUT_FILENAME_HEADER
echo "#define __VERSIONCC__" >> $OUTPUT_FILENAME_HEADER
echo "" >> $OUTPUT_FILENAME_HEADER
echo "#define __BUILD_DATETIME__    \"$TIMESTAMP_ISO\"" >> $OUTPUT_FILENAME_HEADER
echo "#define __BUILD_NUMBER__      ($BUILDNUMBER)" >> $OUTPUT_FILENAME_HEADER
echo "#define __BUILD_DATEYEAR__    ($DATE_YEAR)" >> $OUTPUT_FILENAME_HEADER
echo "#define __BUILD_DATEMONTH__   ($DATE_MONTH)" >> $OUTPUT_FILENAME_HEADER
echo "#define __BUILD_DATEDAY__     ($DATE_DAY)" >> $OUTPUT_FILENAME_HEADER
echo "" >> $OUTPUT_FILENAME_HEADER
echo "#endif /* __VERSIONCC__ */" >> $OUTPUT_FILENAME_HEADER

# echo "/**" > $PATH_OUTPUT_FILENAME_SOURCE
# echo " * @file $OUTPUT_FILENAME_SOURCE" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " * @author fl0mll" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " * @date $DATE" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " * @copyright" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " *" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " * @brief Compiler Definitions generated by (pre) build script" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo " */" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "#include <stdint.h>" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "#include \"versioncc.h\"" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "" >> $PATH_OUTPUT_FILENAME_SOURCE
# #echo "const char __TIMESTAMP_ISO__[] = \"$TIMESTAMP_ISO\";" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "const char __BUILD_DATETIME__[] APPINFO_BUILD_DATETIME_ATTR = \"$TIMESTAMP_ISO\";" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "const uint16_t __BUILD_DATEYEAR__ = $DATE_YEAR;" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "const uint8_t __BUILD_DATEMONTH__ = $DATE_MONTH;" >> $PATH_OUTPUT_FILENAME_SOURCE
# echo "const uint8_t __BUILD_DATEDAY__ = $DATE_DAY;" >> $PATH_OUTPUT_FILENAME_SOURCE