#!/bin/sh
#
# This file will create the $OUTPUT_FILENAME_* with some runtime variables

OUTPUT_FILENAME_HEADER="Inc/ccgen.h"
OUTPUT_FILENAME_SOURCE="versioncc.c"
PATH_OUTPUT_FILENAME_SOURCE="Src/$OUTPUT_FILENAME_SOURCE"

cd ..
PWD=$(pwd)

#export GITHASH="$(git rev-parse --verify HEAD)"
#echo "HASH: $GITHASH"

TIMESTAMP_ISO=$(date -Iseconds)
DATE=$(date +"%Y-%m-%d")

# echo "/**" > $OUTPUT_FILENAME_HEADER
# echo " * @file ccgen.h" >> $OUTPUT_FILENAME_HEADER
# echo " * @author fl0mll" >> $OUTPUT_FILENAME_HEADER
# echo " * @date $DATE" >> $OUTPUT_FILENAME_HEADER
# echo " * @copyright" >> $OUTPUT_FILENAME_HEADER
# echo " *" >> $OUTPUT_FILENAME_HEADER
# echo " * @brief Compiler Definitions generated by (pre) build script" >> $OUTPUT_FILENAME_HEADER
# echo " */" >> $OUTPUT_FILENAME_HEADER
# echo "#ifndef __CCGEN__" >> $OUTPUT_FILENAME_HEADER
# echo "#define __CCGEN__" >> $OUTPUT_FILENAME_HEADER
# #echo "extern const char __TIMESTAMP_ISO__[];" >> $OUTPUT_FILENAME_HEADER
# echo "#define __TIMESTAMP_ISO__    \"$TIMESTAMP_ISO\";" >> $OUTPUT_FILENAME_HEADER
# echo "#endif /* __CCGEN__ */" >> $OUTPUT_FILENAME_HEADER

echo "/**" > $PATH_OUTPUT_FILENAME_SOURCE
echo " * @file $OUTPUT_FILENAME_SOURCE" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " * @author fl0mll" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " * @date $DATE" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " * @copyright" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " *" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " * @brief Compiler Definitions generated by (pre) build script" >> $PATH_OUTPUT_FILENAME_SOURCE
echo " */" >> $PATH_OUTPUT_FILENAME_SOURCE
#echo "#include \"ccgen.h\"" >> $PATH_OUTPUT_FILENAME_SOURCE
echo "#include \"version.h\"" >> $PATH_OUTPUT_FILENAME_SOURCE
echo "" >> $PATH_OUTPUT_FILENAME_SOURCE
#echo "const char __TIMESTAMP_ISO__[] = \"$TIMESTAMP_ISO\";" >> $PATH_OUTPUT_FILENAME_SOURCE
echo "const char BUILD_DATETIME[] APPINFO_BUILD_DATETIME_ATTR = \"$TIMESTAMP_ISO\";" >> $PATH_OUTPUT_FILENAME_SOURCE
